vich_uploader:
    db_driver: orm

    mappings:
       images:
           uri_prefix: /images
           upload_destination: '%kernel.project_dir%/public/images/products'
           # Decide how uploaded files would be renamed
           # https://github.com/dustin10/VichUploaderBundle/blob/1.7.1/Resources/doc/namers.md
           namer:              vich_uploader.namer_uniqid
